name: "Test"
on: [push]

jobs:
  unit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y qtdeclarative5-dev-tools qml-module-qttest
      - name: QmlTestRunner
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          qmltestrunner
