name: "Test"
on: [push]

jobs:
  unit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qtdeclarative5-dev-tools qml-module-qttest libxcb-xinerama0
      - name: QmlTestRunner
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          qmltestrunner
